In [123]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

In [102]:
data=pd.DataFrame({
    'Experience':[1,2,3,4,5,np.nan,7,8,9,10],
    'Education':['High School','Bachelor','Master','PhD','High School',np.nan,'Bachelor','Master','PhD','High School'],
    'Salary':[35000,40000,45000,55000,50000,50000,62000,70000,75000,76000]
})
data

   Experience    Education  Salary
0         1.0  High School   35000
1         2.0     Bachelor   40000
2         3.0       Master   45000
3         4.0          PhD   55000
4         5.0  High School   50000
5         NaN          NaN   50000
6         7.0     Bachelor   62000
7         8.0       Master   70000
8         9.0          PhD   75000
9        10.0  High School   76000

In [103]:
X=data[['Experience','Education']]
y=data['Salary']

In [104]:

num_cols=['Experience']
cat_cols=['Education']
numeric=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])
categorical=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])
categorical

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [105]:
preprocess=ColumnTransformer([
    ('num',numeric,num_cols),
    ('cat',categorical,cat_cols)
])
model=Pipeline(steps=[
    ('preprocess',preprocess),
    ('model',LinearRegression())
])

In [106]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Experience']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Education'])])),
                ('model', LinearRegression())])

In [107]:
y_pred=model.predict(X_test)
y_pred

array([78373.63270006, 38626.36729994])

In [108]:
#Evaluate the model
mae=mean_absolute_error(y_test,y_pred)
rmse=np.sqrt(mean_squared_error(y_test,y_pred))
r2=r2_score(y_test,y_pred)
print('Mean Absolute Error:',round(mae,2))
print('Root Mean Squared Error:',round(rmse,2))
print('R2 Score:',round(r2,2))

Mean Absolute Error: 2373.63
Root Mean Squared Error: 2575.68
R2 Score: 0.98

In [109]:
#predict for new employee
exp=int(input('Enter the experience of the employee:'))
edu=input('Enter the education level of the employee:')
new_employee =pd.DataFrame({
    'Experience':[exp],
    'Education':[edu]
    })
predicted_salary=model.predict(new_employee)
print('Predicted Salary:',round(predicted_salary[0],2))

Enter the experience of the employee:2
Enter the education level of the employee:PhD
Predicted Salary: 45650.55

Build a Machine Learning Pipeline to predict fuel efficiency (km/I) of a car based on Engine Size,HorsePower, and Fuel Type. Evaluate model as well i.e. mae,rmse, r-2.

In [110]:
data = pd.DataFrame({
    "EngineSize": [1.0, 1.2, 1.4, 1.6, 1.8, np.nan, 2.0, 2.2, 2.4, 2.6],
    "HorsePower": [68, 75, 90, 100, 110, 115, np.nan, 130, 150, 160],
    "FuelType": ["Petrol", "Diesel", "Petrol", "Diesel", "Petrol",
                 "Petrol", np.nan, "Diesel", "Petrol", "Diesel"],
    "FuelEfficiency": [20, 22, 19, 25, 18, 21, 23, 26, 17, 24]
})
data

   EngineSize  HorsePower FuelType  FuelEfficiency
0         1.0        68.0   Petrol              20
1         1.2        75.0   Diesel              22
2         1.4        90.0   Petrol              19
3         1.6       100.0   Diesel              25
4         1.8       110.0   Petrol              18
5         NaN       115.0   Petrol              21
6         2.0         NaN      NaN              23
7         2.2       130.0   Diesel              26
8         2.4       150.0   Petrol              17
9         2.6       160.0   Diesel              24

In [111]:
X=data[['EngineSize','HorsePower','FuelType']]
y=data['FuelEfficiency']

In [112]:
num_cols=['EngineSize','HorsePower']
cat_cols=['FuelType']
numeric=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])
categorical=Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])
categorical

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [118]:
numeric=Pipeline([
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',StandardScaler())
])
categorical=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])

In [128]:
preprocess=ColumnTransformer([
    ('num',numeric,num_cols),
    ('cat',categorical,cat_cols)
])
model=Pipeline(steps=[
    ('preprocess',preprocess),
    # ('regressor',SVR(kernel='rbf',C=100,gamma=0.1))
    # ('regressor',GradientBoostingRegressor(n_estimators=100,random_state=42))
    ('regressor',LinearRegression())
    # ('model',RandomForestRegressor(n_estimators=100,random_state=42))
])

In [129]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['EngineSize', 'HorsePower']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['FuelType'])])),
                ('regressor', LinearRegression())])

In [130]:
y_pred=model.predict(X_test)
y_pred

array([18.89758649, 25.53470785])

In [131]:
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)
print('Mean Absolute Error:',round(mae,2))
print('Root Mean Squared Error:',round(rmse,2))
print('Root Mean Squared Error:',round(rmse,2))
print('R2 Score:',round(r2,2))

Mean Absolute Error: 2.72
Root Mean Squared Error: 2.84
Root Mean Squared Error: 2.84
R2 Score: -0.29