**Steps For Modeling:**

1. Creating the Model
2. Compiling th Model
3. Define a loss function
4. Setting up an optimizer
5. Finding best learning size
6. Creating Evalution Metrics
7. Fitting Model
8. Imporve Model

**Predict Heart Disease**
1. Load DataSet
2. Spilt features and Test
3. Train Trest Spil
4. Scale Features

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [4]:
heart_data=pd.read_csv('/content/heart.csv')
heart_data.head()

   age  sex  chol  trestbps  thalach  target
0   52    1   200       130      150       1
1   58    0   240       150      140       1
2   60    1   180       140      145       0
3   48    1   190       120      160       0
4   50    0   220       125      155       1

In [5]:
X=heart_data.drop('target',axis=1)
y=heart_data['target']

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
#creating model
model=tf.keras.Sequential(
    [
        tf.keras.layers.Dense(16,activation='relu', input_shape=(X_train.shape[1],)),
        tf.keras.layers.Dense(8,activation='relu'),
        tf.keras.layers.Dense(1,activation='sigmoid')
    ])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [10]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [11]:
#train the model
histroy_model=model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.8750 - loss: 0.6297 - val_accuracy: 0.5000 - val_loss: 0.6640
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.8750 - loss: 0.6265 - val_accuracy: 0.5000 - val_loss: 0.6628
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 304ms/step - accuracy: 0.8750 - loss: 0.6232 - val_accuracy: 0.5000 - val_loss: 0.6615
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.8750 - loss: 0.6201 - val_accuracy: 0.5000 - val_loss: 0.6603
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.8750 - loss: 0.6169 - val_accuracy: 0.5000 - val_loss: 0.6585
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 267ms/step - accuracy: 0.8750 - loss: 0.6139 - val_accuracy: 0.5000 - val_loss: 0.6566
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.8750 - loss: 0.6107 - val_accuracy: 0.5000 - val_loss: 0.6547
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 322ms/step - accuracy: 0.8750 - loss: 0.6073 - val_accuracy: 1.0000 - val_loss: 0.6528
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 274ms/step - accuracy: 0.8750 - loss: 0.6040 - val_accuracy: 1.0000 - val_loss: 0.6509
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.8750 - loss: 0.6006 - val_accuracy: 1.0000 - val_loss: 0.6490
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.8750 - loss: 0.5972 - val_accuracy: 1.0000 - val_loss: 0.6470
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step - accuracy: 0.8750 - loss: 0.5939 - val_accuracy: 1.0000 - val_loss: 0.6450
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - accuracy: 0.8750 - loss: 0.5905 - val_accuracy: 1.0000 - val_loss: 0.6429
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step - accuracy: 0.8750 - loss: 0.5872 - val_accuracy: 1.0000 - val_loss: 0.6408
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.8750 - loss: 0.5839 - val_accuracy: 1.0000 - val_loss: 0.6387
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8750 - loss: 0.5806 - val_accuracy: 1.0000 - val_loss: 0.6366
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.8750 - loss: 0.5773 - val_accuracy: 1.0000 - val_loss: 0.6346
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8750 - loss: 0.5740 - val_accuracy: 1.0000 - val_loss: 0.6326
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8750 - loss: 0.5707 - val_accuracy: 1.0000 - val_loss: 0.6306
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.8750 - loss: 0.5674 - val_accuracy: 1.0000 - val_loss: 0.6286
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8750 - loss: 0.5640 - val_accuracy: 1.0000 - val_loss: 0.6267
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8750 - loss: 0.5607 - val_accuracy: 1.0000 - val_loss: 0.6248
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.8750 - loss: 0.5574 - val_accuracy: 1.0000 - val_loss: 0.6228
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8750 - loss: 0.5541 - val_accuracy: 1.0000 - val_loss: 0.6207
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.8750 - loss: 0.5507 - val_accuracy: 1.0000 - val_loss: 0.6187
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8750 - loss: 0.5474 - val_accuracy: 1.0000 - val_loss: 0.6166
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8750 - loss: 0.5442 - val_accuracy: 1.0000 - val_loss: 0.6145
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8750 - loss: 0.5409 - val_accuracy: 1.0000 - val_loss: 0.6125
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.8750 - loss: 0.5377 - val_accuracy: 1.0000 - val_loss: 0.6105
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.8750 - loss: 0.5344 - val_accuracy: 1.0000 - val_loss: 0.6084
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8750 - loss: 0.5312 - val_accuracy: 1.0000 - val_loss: 0.6064
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.8750 - loss: 0.5279 - val_accuracy: 1.0000 - val_loss: 0.6044
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8750 - loss: 0.5247 - val_accuracy: 1.0000 - val_loss: 0.6022
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.8750 - loss: 0.5214 - val_accuracy: 1.0000 - val_loss: 0.6001
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.8750 - loss: 0.5182 - val_accuracy: 1.0000 - val_loss: 0.5980
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.8750 - loss: 0.5150 - val_accuracy: 1.0000 - val_loss: 0.5959
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.8750 - loss: 0.5118 - val_accuracy: 1.0000 - val_loss: 0.5938
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.8750 - loss: 0.5086 - val_accuracy: 1.0000 - val_loss: 0.5917
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step - accuracy: 0.8750 - loss: 0.5054 - val_accuracy: 1.0000 - val_loss: 0.5895
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.8750 - loss: 0.5022 - val_accuracy: 1.0000 - val_loss: 0.5873
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 1.0000 - loss: 0.4990 - val_accuracy: 1.0000 - val_loss: 0.5852
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 1.0000 - loss: 0.4959 - val_accuracy: 1.0000 - val_loss: 0.5830
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 1.0000 - loss: 0.4928 - val_accuracy: 1.0000 - val_loss: 0.5808
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 1.0000 - loss: 0.4897 - val_accuracy: 1.0000 - val_loss: 0.5787
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 269ms/step - accuracy: 1.0000 - loss: 0.4865 - val_accuracy: 1.0000 - val_loss: 0.5765
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 1.0000 - loss: 0.4834 - val_accuracy: 1.0000 - val_loss: 0.5743
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 1.0000 - loss: 0.4802 - val_accuracy: 1.0000 - val_loss: 0.5721
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 1.0000 - loss: 0.4769 - val_accuracy: 1.0000 - val_loss: 0.5699
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 1.0000 - loss: 0.4737 - val_accuracy: 1.0000 - val_loss: 0.5677
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.4704 - val_accuracy: 1.0000 - val_loss: 0.5654
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.4672 - val_accuracy: 1.0000 - val_loss: 0.5632
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.4638 - val_accuracy: 1.0000 - val_loss: 0.5613
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 1.0000 - loss: 0.4603 - val_accuracy: 1.0000 - val_loss: 0.5594
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 1.0000 - loss: 0.4567 - val_accuracy: 1.0000 - val_loss: 0.5575
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 1.0000 - loss: 0.4530 - val_accuracy: 1.0000 - val_loss: 0.5555
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 1.0000 - loss: 0.4493 - val_accuracy: 1.0000 - val_loss: 0.5535
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 1.0000 - loss: 0.4455 - val_accuracy: 1.0000 - val_loss: 0.5515
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.4417 - val_accuracy: 1.0000 - val_loss: 0.5494
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.4380 - val_accuracy: 1.0000 - val_loss: 0.5474
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.4342 - val_accuracy: 1.0000 - val_loss: 0.5454
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.4305 - val_accuracy: 1.0000 - val_loss: 0.5434
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.4267 - val_accuracy: 1.0000 - val_loss: 0.5414
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.4229 - val_accuracy: 1.0000 - val_loss: 0.5394
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 1.0000 - loss: 0.4192 - val_accuracy: 1.0000 - val_loss: 0.5373
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 1.0000 - loss: 0.4156 - val_accuracy: 1.0000 - val_loss: 0.5353
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 1.0000 - loss: 0.4122 - val_accuracy: 1.0000 - val_loss: 0.5334
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - accuracy: 1.0000 - loss: 0.4088 - val_accuracy: 1.0000 - val_loss: 0.5316
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - accuracy: 1.0000 - loss: 0.4055 - val_accuracy: 1.0000 - val_loss: 0.5299
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 1.0000 - loss: 0.4021 - val_accuracy: 1.0000 - val_loss: 0.5282
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3988 - val_accuracy: 1.0000 - val_loss: 0.5265
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.3955 - val_accuracy: 1.0000 - val_loss: 0.5249
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3921 - val_accuracy: 1.0000 - val_loss: 0.5232
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.3889 - val_accuracy: 1.0000 - val_loss: 0.5216
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.3857 - val_accuracy: 1.0000 - val_loss: 0.5198
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3825 - val_accuracy: 1.0000 - val_loss: 0.5179
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 1.0000 - loss: 0.3793 - val_accuracy: 1.0000 - val_loss: 0.5159
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 1.0000 - loss: 0.3762 - val_accuracy: 1.0000 - val_loss: 0.5139
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 1.0000 - loss: 0.3730 - val_accuracy: 1.0000 - val_loss: 0.5120
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3698 - val_accuracy: 1.0000 - val_loss: 0.5102
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.3667 - val_accuracy: 1.0000 - val_loss: 0.5084
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.3635 - val_accuracy: 1.0000 - val_loss: 0.5067
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 1.0000 - loss: 0.3604 - val_accuracy: 1.0000 - val_loss: 0.5049
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.3573 - val_accuracy: 1.0000 - val_loss: 0.5031
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 1.0000 - loss: 0.3542 - val_accuracy: 1.0000 - val_loss: 0.5013
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3512 - val_accuracy: 1.0000 - val_loss: 0.4995
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3481 - val_accuracy: 1.0000 - val_loss: 0.4978
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.3451 - val_accuracy: 1.0000 - val_loss: 0.4961
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 1.0000 - loss: 0.3421 - val_accuracy: 1.0000 - val_loss: 0.4945
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 1.0000 - loss: 0.3391 - val_accuracy: 1.0000 - val_loss: 0.4928
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3361 - val_accuracy: 1.0000 - val_loss: 0.4912
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 1.0000 - loss: 0.3331 - val_accuracy: 1.0000 - val_loss: 0.4895
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3301 - val_accuracy: 1.0000 - val_loss: 0.4878
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 1.0000 - loss: 0.3272 - val_accuracy: 1.0000 - val_loss: 0.4862
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.3244 - val_accuracy: 1.0000 - val_loss: 0.4846
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.3215 - val_accuracy: 1.0000 - val_loss: 0.4830
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 1.0000 - loss: 0.3187 - val_accuracy: 1.0000 - val_loss: 0.4814
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3158 - val_accuracy: 1.0000 - val_loss: 0.4800
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 1.0000 - loss: 0.3130 - val_accuracy: 1.0000 - val_loss: 0.4787
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 1.0000 - loss: 0.3103 - val_accuracy: 1.0000 - val_loss: 0.4775
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.3076 - val_accuracy: 1.0000 - val_loss: 0.4763

In [12]:
# Evaluate the Model
loss,accuracy=model.evaluate(X_test,y_test)
print(f'Loss:{loss},Accuracy:{accuracy}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.4763
Loss:0.4763413071632385,Accuracy:1.0


**Example 2**

Bank Customer Exit Prediction.

*  Based on given data using Neural Network Binary Classifier find out is a customer going to stay or leave stay: (Exited=0) and leave (Exited=1).
*   Predict the result for new data as well at end.

In [14]:
#Example
bank_data=pd.read_csv('/content/bank_churn.csv')
bank_data.head()

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,EstimatedSalary,Exited
0,600,France,Male,40,60000,1,50000,0
1,700,Spain,Female,45,70000,2,60000,0
2,800,Germany,Female,38,80000,1,70000,1
3,400,France,Male,30,30000,1,40000,1
4,550,Spain,Male,50,40000,2,42000,0

In [15]:
le=LabelEncoder()
bank_data['Gender']=le.fit_transform(bank_data['Gender'])
bank_data=pd.get_dummies(bank_data,columns=['Geography'])
X=bank_data.drop(['Exited'],axis=1)
y=bank_data['Exited']

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [18]:
bank_model=tf.keras.Sequential(
    [
        tf.keras.layers.Dense(16,activation='relu', input_shape=(X_train.shape[1],)),
        tf.keras.layers.Dense(8,activation='relu'),
        tf.keras.layers.Dense(1,activation='sigmoid')


    ]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [19]:
bank_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#bank_model.summary()

In [20]:
bank_model_history=bank_model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3750 - loss: 0.7110 - val_accuracy: 0.0000e+00 - val_loss: 0.7523
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.3750 - loss: 0.7075 - val_accuracy: 0.0000e+00 - val_loss: 0.7531
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.3750 - loss: 0.7040 - val_accuracy: 0.0000e+00 - val_loss: 0.7539
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step - accuracy: 0.3750 - loss: 0.7006 - val_accuracy: 0.0000e+00 - val_loss: 0.7547
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - accuracy: 0.3750 - loss: 0.6971 - val_accuracy: 0.0000e+00 - val_loss: 0.7555
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 325ms/step - accuracy: 0.3750 - loss: 0.6937 - val_accuracy: 0.0000e+00 - val_loss: 0.7564
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.3750 - loss: 0.6904 - val_accuracy: 0.0000e+00 - val_loss: 0.7572
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - accuracy: 0.3750 - loss: 0.6870 - val_accuracy: 0.0000e+00 - val_loss: 0.7583
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.3750 - loss: 0.6837 - val_accuracy: 0.0000e+00 - val_loss: 0.7595
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.3750 - loss: 0.6804 - val_accuracy: 0.0000e+00 - val_loss: 0.7607
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.3750 - loss: 0.6772 - val_accuracy: 0.0000e+00 - val_loss: 0.7619
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.3750 - loss: 0.6741 - val_accuracy: 0.0000e+00 - val_loss: 0.7630
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.3750 - loss: 0.6711 - val_accuracy: 0.0000e+00 - val_loss: 0.7639
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5000 - loss: 0.6680 - val_accuracy: 0.0000e+00 - val_loss: 0.7648
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5000 - loss: 0.6649 - val_accuracy: 0.0000e+00 - val_loss: 0.7656
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5000 - loss: 0.6618 - val_accuracy: 0.0000e+00 - val_loss: 0.7664
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6250 - loss: 0.6587 - val_accuracy: 0.0000e+00 - val_loss: 0.7671
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.6250 - loss: 0.6561 - val_accuracy: 0.0000e+00 - val_loss: 0.7679
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6250 - loss: 0.6537 - val_accuracy: 0.0000e+00 - val_loss: 0.7686
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6250 - loss: 0.6512 - val_accuracy: 0.0000e+00 - val_loss: 0.7694
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6250 - loss: 0.6487 - val_accuracy: 0.0000e+00 - val_loss: 0.7701
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6250 - loss: 0.6464 - val_accuracy: 0.0000e+00 - val_loss: 0.7710
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6250 - loss: 0.6445 - val_accuracy: 0.0000e+00 - val_loss: 0.7719
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6250 - loss: 0.6425 - val_accuracy: 0.0000e+00 - val_loss: 0.7728
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7500 - loss: 0.6405 - val_accuracy: 0.0000e+00 - val_loss: 0.7738
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.6384 - val_accuracy: 0.0000e+00 - val_loss: 0.7748
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7500 - loss: 0.6363 - val_accuracy: 0.0000e+00 - val_loss: 0.7757
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.6343 - val_accuracy: 0.0000e+00 - val_loss: 0.7767
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.6323 - val_accuracy: 0.0000e+00 - val_loss: 0.7777
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7500 - loss: 0.6303 - val_accuracy: 0.0000e+00 - val_loss: 0.7788
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.6282 - val_accuracy: 0.0000e+00 - val_loss: 0.7798
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.6261 - val_accuracy: 0.0000e+00 - val_loss: 0.7809
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.6240 - val_accuracy: 0.0000e+00 - val_loss: 0.7820
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.6219 - val_accuracy: 0.0000e+00 - val_loss: 0.7831
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.6197 - val_accuracy: 0.0000e+00 - val_loss: 0.7843
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.6178 - val_accuracy: 0.0000e+00 - val_loss: 0.7856
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.6160 - val_accuracy: 0.0000e+00 - val_loss: 0.7869
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7500 - loss: 0.6141 - val_accuracy: 0.0000e+00 - val_loss: 0.7883
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.6121 - val_accuracy: 0.0000e+00 - val_loss: 0.7899
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7500 - loss: 0.6103 - val_accuracy: 0.0000e+00 - val_loss: 0.7915
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7500 - loss: 0.6089 - val_accuracy: 0.0000e+00 - val_loss: 0.7932
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.6075 - val_accuracy: 0.0000e+00 - val_loss: 0.7951
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7500 - loss: 0.6059 - val_accuracy: 0.0000e+00 - val_loss: 0.7970
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7500 - loss: 0.6043 - val_accuracy: 0.0000e+00 - val_loss: 0.7989
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.6027 - val_accuracy: 0.0000e+00 - val_loss: 0.8010
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.6010 - val_accuracy: 0.0000e+00 - val_loss: 0.8031
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.5994 - val_accuracy: 0.0000e+00 - val_loss: 0.8053
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.5976 - val_accuracy: 0.0000e+00 - val_loss: 0.8075
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.5960 - val_accuracy: 0.0000e+00 - val_loss: 0.8097
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.5943 - val_accuracy: 0.0000e+00 - val_loss: 0.8119
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.5926 - val_accuracy: 0.0000e+00 - val_loss: 0.8141
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.5909 - val_accuracy: 0.0000e+00 - val_loss: 0.8163
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.5891 - val_accuracy: 0.0000e+00 - val_loss: 0.8184
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.5873 - val_accuracy: 0.0000e+00 - val_loss: 0.8204
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.7500 - loss: 0.5856 - val_accuracy: 0.0000e+00 - val_loss: 0.8225
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7500 - loss: 0.5838 - val_accuracy: 0.0000e+00 - val_loss: 0.8248
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.5820 - val_accuracy: 0.0000e+00 - val_loss: 0.8272
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.5802 - val_accuracy: 0.0000e+00 - val_loss: 0.8297
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.7500 - loss: 0.5783 - val_accuracy: 0.0000e+00 - val_loss: 0.8322
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7500 - loss: 0.5761 - val_accuracy: 0.0000e+00 - val_loss: 0.8346
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.5737 - val_accuracy: 0.0000e+00 - val_loss: 0.8370
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7500 - loss: 0.5713 - val_accuracy: 0.0000e+00 - val_loss: 0.8393
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.7500 - loss: 0.5688 - val_accuracy: 0.0000e+00 - val_loss: 0.8417
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.5662 - val_accuracy: 0.0000e+00 - val_loss: 0.8441
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.5636 - val_accuracy: 0.0000e+00 - val_loss: 0.8466
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.7500 - loss: 0.5609 - val_accuracy: 0.0000e+00 - val_loss: 0.8491
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7500 - loss: 0.5581 - val_accuracy: 0.0000e+00 - val_loss: 0.8516
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7500 - loss: 0.5553 - val_accuracy: 0.0000e+00 - val_loss: 0.8540
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7500 - loss: 0.5526 - val_accuracy: 0.0000e+00 - val_loss: 0.8564
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.5499 - val_accuracy: 0.0000e+00 - val_loss: 0.8589
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7500 - loss: 0.5471 - val_accuracy: 0.0000e+00 - val_loss: 0.8615
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - accuracy: 0.7500 - loss: 0.5442 - val_accuracy: 0.0000e+00 - val_loss: 0.8642
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.7500 - loss: 0.5415 - val_accuracy: 0.0000e+00 - val_loss: 0.8669
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - accuracy: 0.7500 - loss: 0.5386 - val_accuracy: 0.0000e+00 - val_loss: 0.8695
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 177ms/step - accuracy: 0.7500 - loss: 0.5357 - val_accuracy: 0.0000e+00 - val_loss: 0.8721
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - accuracy: 0.7500 - loss: 0.5328 - val_accuracy: 0.0000e+00 - val_loss: 0.8748
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 306ms/step - accuracy: 0.7500 - loss: 0.5300 - val_accuracy: 0.0000e+00 - val_loss: 0.8776
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.7500 - loss: 0.5270 - val_accuracy: 0.0000e+00 - val_loss: 0.8806
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - accuracy: 0.7500 - loss: 0.5241 - val_accuracy: 0.0000e+00 - val_loss: 0.8836
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.7500 - loss: 0.5213 - val_accuracy: 0.0000e+00 - val_loss: 0.8864
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step - accuracy: 0.7500 - loss: 0.5184 - val_accuracy: 0.0000e+00 - val_loss: 0.8899
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 299ms/step - accuracy: 0.7500 - loss: 0.5153 - val_accuracy: 0.0000e+00 - val_loss: 0.8936
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step - accuracy: 0.7500 - loss: 0.5124 - val_accuracy: 0.0000e+00 - val_loss: 0.8973
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.7500 - loss: 0.5095 - val_accuracy: 0.0000e+00 - val_loss: 0.9011
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.5065 - val_accuracy: 0.0000e+00 - val_loss: 0.9049
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7500 - loss: 0.5036 - val_accuracy: 0.0000e+00 - val_loss: 0.9088
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.7500 - loss: 0.5007 - val_accuracy: 0.0000e+00 - val_loss: 0.9126
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.7500 - loss: 0.4977 - val_accuracy: 0.0000e+00 - val_loss: 0.9164
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7500 - loss: 0.4948 - val_accuracy: 0.0000e+00 - val_loss: 0.9204
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - accuracy: 0.7500 - loss: 0.4919 - val_accuracy: 0.0000e+00 - val_loss: 0.9243
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - accuracy: 0.7500 - loss: 0.4889 - val_accuracy: 0.0000e+00 - val_loss: 0.9284
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - accuracy: 0.7500 - loss: 0.4860 - val_accuracy: 0.0000e+00 - val_loss: 0.9324
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 300ms/step - accuracy: 0.7500 - loss: 0.4831 - val_accuracy: 0.0000e+00 - val_loss: 0.9364
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 264ms/step - accuracy: 0.7500 - loss: 0.4804 - val_accuracy: 0.0000e+00 - val_loss: 0.9405
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 0.7500 - loss: 0.4776 - val_accuracy: 0.0000e+00 - val_loss: 0.9447
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - accuracy: 0.7500 - loss: 0.4747 - val_accuracy: 0.0000e+00 - val_loss: 0.9490
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - accuracy: 0.7500 - loss: 0.4718 - val_accuracy: 0.0000e+00 - val_loss: 0.9533
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.7500 - loss: 0.4690 - val_accuracy: 0.0000e+00 - val_loss: 0.9576
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.7500 - loss: 0.4662 - val_accuracy: 0.0000e+00 - val_loss: 0.9619
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.7500 - loss: 0.4632 - val_accuracy: 0.0000e+00 - val_loss: 0.9662

In [21]:
new_customer = pd.DataFrame({
    "CreditScore": [720],
    "Geography": ["France"],
    "Gender": ["Male"],
    "Age": [42],
    "Balance": [62000],
    "NumOfProducts": [1],
    "EstimatedSalary": [55000]
})

# Encode and scale same as before
new_customer["Gender"] = le.transform(new_customer["Gender"])
new_customer = pd.get_dummies(new_customer, columns=["Geography"], drop_first=True)

# Add missing dummy columns
for col in [c for c in X.columns if c not in new_customer.columns]:
    new_customer[col] = 0

new_customer = new_customer[X.columns]  # same order
new_scaled = scaler.transform(new_customer)

# Predict
pred =bank_model.predict(new_scaled)
if pred[0][0] > 0.5:
    print("Customer will leave")
    print(pred[0][0])
else:
    print("Customer will stay")
    print(pred[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
Customer will stay
0.41005805